(function (root) {
  var GDS = root.GDS = root.GDS || {};
  GDS.sim = GDS.sim || {};
  GDS.sim.ERR = {
    HIRE_CAP_FULL: "HIRE_CAP_FULL",
    HIRE_NOT_FOUND: "HIRE_NOT_FOUND",
    FIRE_BUSY: "FIRE_BUSY",
    FIRE_NOT_FOUND: "FIRE_NOT_FOUND",
    RELOCATE_MAX: "RELOCATE_MAX",
    RELOCATE_FUNDS: "RELOCATE_FUNDS",
    AD_FUNDS: "AD_FUNDS",
    STUDIO_SCALE: "STUDIO_SCALE",
    STUDIO_NO_LEAD: "STUDIO_NO_LEAD",
    PITCH_NO_STAFF: "PITCH_NO_STAFF",
    PITCH_NO_PRODUCER: "PITCH_NO_PRODUCER",
    PITCH_TEAM_SIZE: "PITCH_TEAM_SIZE",
    PITCH_LIVEOPS_SCALE: "PITCH_LIVEOPS_SCALE",
    PITCH_BUSY: "PITCH_BUSY",
    PITCH_PLATFORM: "PITCH_PLATFORM",
    PITCH_OUTSOURCE_CAP: "PITCH_OUTSOURCE_CAP",
    LIVEOPS_NOT_FOUND: "LIVEOPS_NOT_FOUND",
    LIVEOPS_INACTIVE: "LIVEOPS_INACTIVE",
    LIVEOPS_STAFF_BUSY: "LIVEOPS_STAFF_BUSY",
    RELEASE_NOT_FOUND: "RELEASE_NOT_FOUND",
    RELEASE_NOT_PLAYING: "RELEASE_NOT_PLAYING",
    EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
    EVENT_NOT_CHOICE: "EVENT_NOT_CHOICE",
    EVENT_OPTION_INVALID: "EVENT_OPTION_INVALID"
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
