(function (root) {
  var GDS = root.GDS = root.GDS || {};
  GDS.sim = GDS.sim || {};
  GDS.sim.ERR = {
    EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
    EVENT_NOT_CHOICE: "EVENT_NOT_CHOICE",
    EVENT_OPTION_INVALID: "EVENT_OPTION_INVALID",
    CAREER_ROLE_INVALID: "CAREER_ROLE_INVALID",
    CAREER_OFFER_NOT_FOUND: "CAREER_OFFER_NOT_FOUND",
    CAREER_NOT_CAREER: "CAREER_NOT_CAREER",
    CAREER_ALREADY_HIRED: "CAREER_ALREADY_HIRED",
    CAREER_BUSY: "CAREER_BUSY",
    CAREER_HOP_WAIT: "CAREER_HOP_WAIT",
    CAREER_HOP_NO_PICK: "CAREER_HOP_NO_PICK",
    CAREER_INVITE_NOT_FOUND: "CAREER_INVITE_NOT_FOUND",
    CAREER_NOT_JOINABLE: "CAREER_NOT_JOINABLE",
    CAREER_PROMOTE_LOCKED: "CAREER_PROMOTE_LOCKED",
    CAREER_LINE_LOCKED: "CAREER_LINE_LOCKED",
    CAREER_FOUNDER_LOCKED: "CAREER_FOUNDER_LOCKED"
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
